### ISSUE TITLE
Eat Out- Zomato API response objects

### ISSUE THREAD

**Issue by jayjscotto** [jayjscotto/in-or-out#12]
Create an Array of lists of 20+ cities (maybe we can do 10+ popular cities in this area) that contains each city's unique ID for the Zomato API.

Maybe we can adjust to specify the city on Zomato search at a later date.

**Comment by jayjscotto** [comment]
---Zomato API Object response:
response.restaurants[i].location.address + .city
response.restaurants[i].location.name
response.restaurants[i].offers.phone_numbers (array...)
response.restaurants[i].price_range (maybe print a $ sign for each

**Comment by wseide** [comment]
Made the search dynamic so we can now search any city to get a response
